<form class="log-in-form" method="POST"
action="/receptikorisnik/promjenarecepta">

  <div class="form-group">
    <label for="naziv">NAZIV</label>
    <input type="text" class="form-control" id="naziv" name="naziv" value="
    <?php 
    echo $recepti->naziv;
    ?>
    "> 
  </div>

  <div class="form-group">
    <label for="kolicina">KOLIČINA</label>
    <input type="text" class="form-control" id="kolicina" name="kolicina" value="
    <?php 
    echo $recepti->kolicina;
    ?>
    ">
  </div>

  <div class="form-group">
    <label for="text">SASTOJCI</label>
    <textarea class="form-control" id="sastojci" name="sastojci" rows="2">
    <?php 
    echo $recepti->sastojci;
    ?>
    </textarea>
  </div>

  <div class="form-group">
    <label for="text">PRIPREMA </label>
    <textarea class="form-control" id="opis" name="opis" rows="6">
    <?php 
    echo $recepti->opis;
    ?>
    </textarea>  
  </div>

  <div class="grid-x grid-margin-x">
    <div class="large-6 cell">
      <a href="/receptikorisnik/index" class="alert button expanded">Odustani</a>
    </div>
    <div class="large-6 cell">
      <input type="submit" class="button expanded" value="Izvrši izmjene na receptu"></input>
    </div>
  </div>
 
  <input type="hidden" name="sifra" 
  value="<?php echo $sifra; ?>">
</form>
<?php echo $message; ?>