 
<h2>Registrirani korisnici:</h2>
<table>
    <thead>
        <tr>
            <th>
                Ime i prezime
            </th>
            <th>
                Korisničko ime
            </th>
            <th>
                Email
            </th>
            <th>
                Akcija
            </th>
        </tr>
    </thead>
    <tbody>
    <?php
        foreach($registrationtable as $red){
            include 'tableusers.phtml';
        }
    ?>
    <hr/>
    </tbody>
</table>

 