<tr>
    <td><?php echo $red->ime . ' ' . $red->prezime ?></td>
    <td><?php echo $red->username ?></td>
    <td><?php echo $red->email ?></td>
    <td> 
    <a href="/adminzidar/changes?sifra=<?php echo $red->sifra?>"><i title="Promjeni" class="fas fa-edit fa-1x"style="font-size: 1.3em;"></i></a> 
<a onclick="return confirm('Sigurno obrisati <?php echo $red->ime . ' ' . $red->prezime ?>?')" 
          href="/adminzidar/delete?sifra=<?php echo $red->sifra ?>"><i title="Obriši" class="fas fa-user-times fa-1x " 
          style="font-size: 1.3em; color: red;"></i></a>
    </td>
</tr>




