<tr>
    <td><?php echo $red->ime . ' ' . $red->prezime ?></td>
    <td><?php echo $red->username ?></td>
    <td><?php echo $red->email ?></td>
    <td>
    <!-- srediti jebenu ikonicu --> <a onclick="return confirm('Sigurno obrisati <?php echo $red->ime . ' ' . $red->prezime ?>?')" 
          href="/adminzidar/delete?password=<?php echo $red->password ?>"><i title="Obriši" class="fas fa-user-times fa-1x " 
          style="font-size: 1.3em; color: red;"></i></a>
    </td>
</tr>