<footer>
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-4">
                    <div id="lijevo"class="<?php echo Initialapp::configuration('dev') ? 'alert' : 'warning'; ?> callout"> 
        &copy; <?php echo Initialapp::configuration('nazivAPP'); ?> 2019 - <?php echo date('yy'); ?></div>
                </div>
                <div class="col-4">
                    <div id="desno" class="text-right"></div>
                </div>
            </div>
        </div>

    </footer>