<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Zidar">

    <title><?php echo Initialapp::configuration('nazivAPP'); ?></title>


    <link rel="canonical" href="<?php echo Initialapp::configuration('url'); ?>">
<!--tiny mce podesavanje-->
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
  tinymce.init({
    selector: 'textarea'
  });
  </script>


    <link href="<?php echo Initialapp::configuration('url'); ?>public/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo Initialapp::configuration('url'); ?>public/css/moj.css" rel="stylesheet">
    
    
    <link rel="icon" href="<?php echo Initialapp::configuration('url'); ?>public/img/favicon.png">
    <meta name="theme-color" content="#563d7c">

    
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>

</head>
