

    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #e3f2fd;">
    <div class="title-bar-title "><?php echo InitialApp::configuration('nazivAPP'); ?></div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" 
  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" 
        aria-expanded="false">
          Recepti
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

     <?php $kategorija=Kategorija::readAll();
     foreach ($kategorija as $kat):?>

          <a class="dropdown-item" href="#"><?php echo $kat->katjela; ?></a>
<?php if (next($kategorija)==true) {
  echo '<div class="dropdown-divider"></div>';
} ?>
     <?php endforeach; ?>
       
        </div>
      </li>
      <?php
                    if(isset($_SESSION['registracija']) && ($_SESSION['registracija']->username==='AdminZidar')):
                ?>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" 
        aria-expanded="false">Admin izbornik
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/adminzidar/index">Registrirani korisnici</a> <!-- ne prebacuje na index.phtml od admina -->
         
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Recepti</a>
        </div>
      </li>
      <?php
                    endif;
                ?>
      

      <li class="nav-item">
      <?php if(!isset($_SESSION['registracija'])): ?>
    <a class="nav-link" href="/index/login">Prijava</a>
      <?php else:?>
        <a class="nav-link" href="/index/logout">Odjavi 
        <?php echo $_SESSION['registracija']->username;?> </a>
      <?php endif;?>
  </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Pretraži</button>
    </form>
  </div>
</nav>
