<form class="log-in-form" method="POST"
action="/adminzidar/changeregistration">
 <label>Korisničko ime
    <input type="text" id="username" name="username" value="<?php 
    echo $registracija->username;
    ?>">
  </label>
  </label>
  <label>Email
    <input type="email" id="email" name="email" value="<?php 
    echo $registracija->email;
    ?>">
  </label>
  
  <label>Ime
    <input type="text" id="ime" name="ime" value="<?php 
    echo $registracija->ime;
    ?>">
  </label>

  <label>Prezime
    <input type="text" id="prezime" name="prezime" value="<?php 
    echo $registracija->prezime;
    ?>">
  
  

  <div class="grid-x grid-margin-x">
    <div class="large-6 cell">
      <a href="/adminzidar/index" class="alert button expanded">Odustani</a>
    </div>
    <div class="large-6 cell">
      <input type="submit" class="button expanded" value="Promjeni registriranog korisnika"></input>
    </div>
  </div>
 
  <input type="hidden" name="sifra" 
  value="<?php echo $sifra; ?>">
</form>
<?php echo $message; ?>